server:
  port: 4004 # Gateway listens on port 4004 - this is the entry point for the API Gateway

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Route for /api/patients/** to patient-service
                    # REST-CLIENT ---> http://localhost:4004/api/patients/**
                    # Reroute via API-GATEWAY  --> http://patient-service:4000/patients/**
                    - id: patient-service-route
                      uri: http://patient-service:4000
                      predicates:
                        - Path=/api/patients/**
                      filters:
                        - StripPrefix=1

                      # REST-CLIENT ---> http://localhost:4004/auth/**
                      # Reroute via API-GATEWAY  --> http://auth-service:4005/**
                      #Http --> Https
                    - id: auth-service-route
                      uri: http://auth-service-2:4005
                      predicates:
                        - Path=/auth/**
                      filters:
                        - StripPrefix=1

                    # Route for /api/docs/patients to patient-service /v3/api-docs
                    # REST-CLIENT ---> http://localhost:4004/api-docs/patients
                    # Reroute via API-GATEWAY  --> https://patient-service:4000/v3/api-docs
                    - id: api-docs-patient-route
                      uri: http://patient-service:4000
                      predicates:
                        - Path=/api-docs/patients
                      filters:
                        - RewritePath=/api-docs/patients,/v3/api-docs
