server:
  port: 4004 # Gateway listens on port 4004 - this is the entry point for the API Gateway

# Dummy configuration for the authentication service
auth:
  service:
    url: http://host.docker.internal:4005 # URL of the authentication service
#    jwt:
#      secret: your_jwt_secret_key # Secret key for JWT validation
#      issuer: your_jwt_issuer # Issuer of the JWT token

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Route for /api/patients/** to patient-service
                    # REST-CLIENT ---> http://localhost:4004/api/patients/**
                    # Reroute via API-GATEWAY  --> http://patient-service:4000/patients/**
                    - id: patient-service-route
                      uri: http://host.docker.internal:4000
                      predicates:
                        - Path=/api/patients/**
                      filters:
                        - StripPrefix=1
                        - JwtValidation

                      # REST-CLIENT ---> http://localhost:4004/auth/**
                      # Reroute via API-GATEWAY  --> http://auth-service:4005/**
                      #Http --> Https
                    - id: auth-service-route
                      uri: http://host.docker.internal:4005
                      predicates:
                        - Path=/auth/**
                      filters:
                        - StripPrefix=1

                    # Route for /api/docs/patients to patient-service /v3/api-docs
                    # REST-CLIENT ---> http://localhost:4004/api-docs/patients
                    # Reroute via API-GATEWAY  --> https://patient-service:4000/v3/api-docs
                    - id: api-docs-patient-route
                      uri: http://host.docker.internal:4000
                      predicates:
                        - Path=/api-docs/patients
                      filters:
                        - RewritePath=/api-docs/patients,/v3/api-docs

                    # Route for /api/docs/auth to patient-service /v3/api-docs
                    # REST-CLIENT ---> http://localhost:4004/api-docs/auth
                    # Reroute via API-GATEWAY  --> http://auth-service-2:4005/v3/api-docs
                    - id: api-docs-patient-route
                      uri: http://host.docker.internal:4005
                      predicates:
                        - Path=/api-docs/auth
                      filters:
                        - RewritePath=/api-docs/auth,/v3/api-docs