### POST request to create a new patient
POST http://localhost:4000/patients
Content-Type: application/json

{
"name": "Kishal",
"address": "#1 ABC Street",
"email" : "abc@email.com",
"dateOfBirth":"2000-01-02",
"registeredDate":"2025-01-05"
}
